### ISSUE TITLE
how to deal with the error: record too large

### ISSUE THREAD

**Issue by nookery** [apple/sample-cloudkit-sync-engine#7]
Use the SyncEngine to send data of SwiftData:
`Error saving record <CKRecordID: 0x157e29b10; recordName=1959852C-DAEA-4076-B955-7940D31EBD33, zoneID=Shadow:__defaultOwner__> to server: record too large`

**Comment by timimahoney** [comment]
Each `CKRecord` can only have a limited amount of data in it:

https://developer.apple.com/documentation/cloudkit/ckrecord

> To ensure the speed of fetching and saving records, the data that a record stores must not exceed 1 MB. Assets don’t count toward this limit, but all other data types do.

If you're storing large binary blobs in your records, you might consider using a `CKAsset` instead of `Data`.
